/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-12-06 at 13:33:45 UTC 
 * Modify at your own risk.
 */

package com.deakishin.zodiac.cipherboardendpoint.model;

/**
 * Model definition for DSCipher.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the cipherboardendpoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DSCipher extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long authorId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cipherMarkup;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime date;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean deleted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float difficulty;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean maxSolved;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxSolvedCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer rate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float reward;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String solution;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean solved;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long solvedById;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer solvedCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer solvingCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getAuthorId() {
    return authorId;
  }

  /**
   * @param authorId authorId or {@code null} for none
   */
  public DSCipher setAuthorId(java.lang.Long authorId) {
    this.authorId = authorId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCipherMarkup() {
    return cipherMarkup;
  }

  /**
   * @param cipherMarkup cipherMarkup or {@code null} for none
   */
  public DSCipher setCipherMarkup(java.lang.String cipherMarkup) {
    this.cipherMarkup = cipherMarkup;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDate() {
    return date;
  }

  /**
   * @param date date or {@code null} for none
   */
  public DSCipher setDate(com.google.api.client.util.DateTime date) {
    this.date = date;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getDeleted() {
    return deleted;
  }

  /**
   * @param deleted deleted or {@code null} for none
   */
  public DSCipher setDeleted(java.lang.Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public DSCipher setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getDifficulty() {
    return difficulty;
  }

  /**
   * @param difficulty difficulty or {@code null} for none
   */
  public DSCipher setDifficulty(java.lang.Float difficulty) {
    this.difficulty = difficulty;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public DSCipher setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getMaxSolved() {
    return maxSolved;
  }

  /**
   * @param maxSolved maxSolved or {@code null} for none
   */
  public DSCipher setMaxSolved(java.lang.Boolean maxSolved) {
    this.maxSolved = maxSolved;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxSolvedCount() {
    return maxSolvedCount;
  }

  /**
   * @param maxSolvedCount maxSolvedCount or {@code null} for none
   */
  public DSCipher setMaxSolvedCount(java.lang.Integer maxSolvedCount) {
    this.maxSolvedCount = maxSolvedCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getRate() {
    return rate;
  }

  /**
   * @param rate rate or {@code null} for none
   */
  public DSCipher setRate(java.lang.Integer rate) {
    this.rate = rate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getReward() {
    return reward;
  }

  /**
   * @param reward reward or {@code null} for none
   */
  public DSCipher setReward(java.lang.Float reward) {
    this.reward = reward;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSolution() {
    return solution;
  }

  /**
   * @param solution solution or {@code null} for none
   */
  public DSCipher setSolution(java.lang.String solution) {
    this.solution = solution;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getSolved() {
    return solved;
  }

  /**
   * @param solved solved or {@code null} for none
   */
  public DSCipher setSolved(java.lang.Boolean solved) {
    this.solved = solved;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getSolvedById() {
    return solvedById;
  }

  /**
   * @param solvedById solvedById or {@code null} for none
   */
  public DSCipher setSolvedById(java.lang.Long solvedById) {
    this.solvedById = solvedById;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSolvedCount() {
    return solvedCount;
  }

  /**
   * @param solvedCount solvedCount or {@code null} for none
   */
  public DSCipher setSolvedCount(java.lang.Integer solvedCount) {
    this.solvedCount = solvedCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSolvingCount() {
    return solvingCount;
  }

  /**
   * @param solvingCount solvingCount or {@code null} for none
   */
  public DSCipher setSolvingCount(java.lang.Integer solvingCount) {
    this.solvingCount = solvingCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public DSCipher setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  @Override
  public DSCipher set(String fieldName, Object value) {
    return (DSCipher) super.set(fieldName, value);
  }

  @Override
  public DSCipher clone() {
    return (DSCipher) super.clone();
  }

}
