/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-12-06 at 13:33:45 UTC 
 * Modify at your own risk.
 */

package com.deakishin.zodiac.cipherboardendpoint.model;

/**
 * Model definition for DTOSolutionCheckingResult.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the cipherboardendpoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DTOSolutionCheckingResult extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean alreadySolved;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean correct;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean firstToSolve;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean ownCipher;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float reward;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer solvedOrdinal;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAlreadySolved() {
    return alreadySolved;
  }

  /**
   * @param alreadySolved alreadySolved or {@code null} for none
   */
  public DTOSolutionCheckingResult setAlreadySolved(java.lang.Boolean alreadySolved) {
    this.alreadySolved = alreadySolved;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCorrect() {
    return correct;
  }

  /**
   * @param correct correct or {@code null} for none
   */
  public DTOSolutionCheckingResult setCorrect(java.lang.Boolean correct) {
    this.correct = correct;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getFirstToSolve() {
    return firstToSolve;
  }

  /**
   * @param firstToSolve firstToSolve or {@code null} for none
   */
  public DTOSolutionCheckingResult setFirstToSolve(java.lang.Boolean firstToSolve) {
    this.firstToSolve = firstToSolve;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getOwnCipher() {
    return ownCipher;
  }

  /**
   * @param ownCipher ownCipher or {@code null} for none
   */
  public DTOSolutionCheckingResult setOwnCipher(java.lang.Boolean ownCipher) {
    this.ownCipher = ownCipher;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getReward() {
    return reward;
  }

  /**
   * @param reward reward or {@code null} for none
   */
  public DTOSolutionCheckingResult setReward(java.lang.Float reward) {
    this.reward = reward;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSolvedOrdinal() {
    return solvedOrdinal;
  }

  /**
   * @param solvedOrdinal solvedOrdinal or {@code null} for none
   */
  public DTOSolutionCheckingResult setSolvedOrdinal(java.lang.Integer solvedOrdinal) {
    this.solvedOrdinal = solvedOrdinal;
    return this;
  }

  @Override
  public DTOSolutionCheckingResult set(String fieldName, Object value) {
    return (DTOSolutionCheckingResult) super.set(fieldName, value);
  }

  @Override
  public DTOSolutionCheckingResult clone() {
    return (DTOSolutionCheckingResult) super.clone();
  }

}
